- name: Adds nginx ppa
  apt_repository:
    repo=ppa:nginx/stable

- name: Adds PPA key
  apt_key:
    url=http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x00A6F0A3C300EE8C
    state=present

- name: Installs nginx
  apt:
    pkg=nginx-full
    state=latest
  register: just_installed

- name: Writes nginx.conf
  template:
    src: "../templates/nginx.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart nginx

- name: Removes nginx default server link
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Removes nginx default server
  file:
    path: /etc/nginx/sites-available/default
    state: absent
  notify: Restart nginx

- name: Writes nginx.conf
  template:
    src: "../templates/nginx.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart nginx

- name: Replaces logrotate entry
  template:
    src: logrotate_nginx.j2
    dest: /etc/logrotate.d/nginx
    mode: 0644

- name: Enables nginx at start
# service module is severely broken on 14.04
#  service: name=nginx enabled=yes
  command: update-rc.d nginx defaults
  when: just_installed|changed

